version: "3.5"
services:


  database:
    image: postgres:11
    env_file:
      - ../env/common.env
      - ../env/postgres.env
    volumes:
      - ../postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  default:
    name: dbt-net